services:
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: |
      pip install -r requirements.txt
      ./install_chrome.sh   # Run the script to install Chrome
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT